### ISSUE TITLE
actual distances

### ISSUE THREAD

**Issue by vincefernando** [stefankoegl/kdtree#15]
Is it possible to get the minimum distance (squared) after search_nn without recalculating it?. For higher dimensional trees, distance recalculations could be expensive and should be avoided.

The same question for search_knn and search_nn_dist.

**Comment by Sadabrata** [comment]
Search_nn_dist seems to return the neighbouring points. However, in many cases, the distance of neighbours are also required. So after getting the nearest neighbours using search_nn_dist, I have to recompute their distance from the given point. It will be very good to have the distance of the neighbours returned along with the points.
What I mean is tree.search_nn_dist(point, distance=5) to return (node, distance) just like search_knn

**Comment by harish1996** [comment]
> Search_nn_dist seems to return the neighbouring points. However, in many cases, the distance of neighbours are also required. So after getting the nearest neighbours using search_nn_dist, I have to recompute their distance from the given point. It will be very good to have the distance of the neighbours returned along with the points.
> What I mean is tree.search_nn_dist(point, distance=5) to return (node, distance) just like search_knn

I have sent a pull request implementing the same in #49. Check it out.
