### ISSUE TITLE
A question in _search_node()

### ISSUE THREAD

**Issue by ChaoMai** [stefankoegl/kdtree#27]
When adding new a node to `results`([at line 480](https://github.com/stefankoegl/kdtree/blob/master/kdtree.py#L480)), why don't you **pop the node that has the highest distance** if the length of `results` is `k`?

**Comment by stefankoegl** [comment]
I haven't touched this code in quite some time, so I am not totally sure. However it seems that what you suggest might be the correct thing to do.

Can you submit a pull request with the suggested change?

**Comment by ChaoMai** [comment]
Any way, thank you. I'll modify the code and do some tests to verify my guess.
