### ISSUE TITLE
search_knn() is returning multiple values for k=1 also it is very slower than search_nn()

### ISSUE THREAD

**Issue by vampcoder** [stefankoegl/kdtree#29]
I have been trying to use it for RRT-star implementation, it has increased the time complexity. Also for search_knn(), it is not returning list of length k.

**Comment by stefankoegl** [comment]
I have just released version 0.13, which should bring considerable performance improvements. It should also address the bug related to the number of results of ``search_knn``. If this is still a problem, please reopen the bug and provide some steps to reproduce the issue. Thanks!

**Comment by vampcoder** [comment]
I have implemented my own version. Though, thanks for you response :+1:
