### ISSUE TITLE
Return None when remove the root node

### ISSUE THREAD

**Issue by changle0703** [stefankoegl/kdtree#50]
Return None when remove the root node

**Comment by younik** [comment]
Use 

`tree = tree.remove(point)`

instead of

`tree.remove(point)`

**Comment by changle0703** [comment]
> 
> 
> Use
> 
> `tree = tree.remove(point)`
> 
> instead of
> 
> `tree.remove(point)`

Yes of course, I was just suggesting a tiny modification of the definition of remove
